// Code generated by mockery v2.10.2. DO NOT EDIT.

package handlers

import (
	domain "github.com/AndreyAndreevich/examples-go/integration_tests/domain"
	mock "github.com/stretchr/testify/mock"
)

// logicIntMock is an autogenerated mock type for the logicInt type
type logicIntMock struct {
	mock.Mock
}

// AddBalance provides a mock function with given fields: id, amount
func (_m *logicIntMock) AddBalance(id int, amount float64) (domain.User, error) {
	ret := _m.Called(id, amount)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(int, float64) domain.User); ok {
		r0 = rf(id, amount)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, float64) error); ok {
		r1 = rf(id, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: name, balance
func (_m *logicIntMock) CreateUser(name string, balance float64) (domain.User, error) {
	ret := _m.Called(name, balance)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(string, float64) domain.User); ok {
		r0 = rf(name, balance)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(name, balance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: id
func (_m *logicIntMock) GetUser(id int) (domain.User, error) {
	ret := _m.Called(id)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(int) domain.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
