// Code generated by mockery v2.11.0. DO NOT EDIT.

package handlers

import (
	context "context"

	domain "github.com/AndreyAndreevich/examples-go/integration_tests/domain"
	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// logicIntMock is an autogenerated mock type for the logicInt type
type logicIntMock struct {
	mock.Mock
}

// AddBalance provides a mock function with given fields: ctx, id, amount
func (_m *logicIntMock) AddBalance(ctx context.Context, id int, amount decimal.Decimal) (domain.User, error) {
	ret := _m.Called(ctx, id, amount)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, int, decimal.Decimal) domain.User); ok {
		r0 = rf(ctx, id, amount)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, decimal.Decimal) error); ok {
		r1 = rf(ctx, id, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *logicIntMock) CreateUser(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _m.Called(ctx, user)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *logicIntMock) GetUser(ctx context.Context, id int) (domain.User, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newLogicIntMock creates a new instance of logicIntMock. It also registers a cleanup function to assert the mocks expectations.
func newLogicIntMock(t testing.TB) *logicIntMock {
	mock := &logicIntMock{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
