// Code generated by mockery v2.30.16. DO NOT EDIT.

package time_provider

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// TimeProviderMock is an autogenerated mock type for the TimeProvider type
type TimeProviderMock struct {
	mock.Mock
}

// Now provides a mock function with given fields:
func (_m *TimeProviderMock) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// NewTimeProviderMock creates a new instance of TimeProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeProviderMock {
	mock := &TimeProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
